---
name: "Deploy host native"
on:
  workflow_call:
    inputs:
      SERVER_IP:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      BRANCH:
        required: true
        type: string
      HOSTNAME:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_KEY:
        required: true
      AWS_REGION:
        required: true
      SERVER_SSH_PRIVATE_KEY:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.BRANCH }}

      - name: create a file of the private key ansible_ssh_private_key_file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
      
      - name: setup AWS 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: install ansible
        run: |
          sudo apt install software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible

      - name: Run ansible deploy playbook
        run: ANSIBLE_HOST_KEY_CHECKING=false ansible-playbook .infra/playbooks/deploy.yml -i ${{ inputs.SERVER_IP }}, -e "hostname=${{ inputs.HOSTNAME }}"  --private-key ~/.ssh/id_rsa

