name: "Deploy Production"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/deploy-hostnative.yml
    with:
      SERVER_IP:    "51.44.25.26"
      ENVIRONMENT:  "production"
      BRANCH:       "main"
      SSH_USER:    "ubuntu"
      HOSTNAME: "oyoutube.duckdns.org"
    secrets:
      AWS_ACCESS_KEY:   "${{ secrets.AWS_ACCESS_KEY }}"
      AWS_SECRET_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      AWS_REGION:      "${{ secrets.AWS_REGION }}"
      SERVER_SSH_PRIVATE_KEY: "${{ secrets.SERVER_SSH_PRIVATE_KEY}}"

