---
name: "Deploy host native"
on:
  workflow_call:
    inputs:
      SERVER_IP:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      BRANCH:
        required: true
        type: string
      HOSTNAME:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_KEY:
        required: true
      AWS_REGION:
        required: true
      SERVER_SSH_PRIVATE_KEY:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.BRANCH }}